/* *****************************************
 * CSCI205 - Software Engineering and Design
 * Fall 2015
 * Instructor: Prof Peck
 * Section: 8am
 *
 * Name: Stephanie Garboski, Leonardo Viglino, Anmol Singh,
 Luis Felipe Tomazini
 * Date:
 *
 * Brozingos Poker:
 *
 * Description:
 *
 * *****************************************/
package View;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author sag033
 */
public class GameTable extends javax.swing.JFrame {

    /**
     * Creates new form GameTable
     */
    public GameTable() throws IOException {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        foldCheckBetGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        flop = new javax.swing.JLabel();
        flop1 = new javax.swing.JLabel();
        flop2 = new javax.swing.JLabel();
        TURN = new javax.swing.JLabel();
        RIVER = new javax.swing.JLabel();
        deck = new javax.swing.JLabel();
        card1b = new javax.swing.JButton();
        card2b = new javax.swing.JButton();
        p2c1 = new javax.swing.JLabel();
        p2c2 = new javax.swing.JLabel();
        p3c1 = new javax.swing.JLabel();
        p3c2 = new javax.swing.JLabel();
        p4c1 = new javax.swing.JLabel();
        p4c2 = new javax.swing.JLabel();
        p5c1 = new javax.swing.JLabel();
        p5c2 = new javax.swing.JLabel();
        p6c1 = new javax.swing.JLabel();
        p6c2 = new javax.swing.JLabel();
        whiteChip = new javax.swing.JLabel();
        blackChip = new javax.swing.JLabel();
        redChip = new javax.swing.JLabel();
        blueChip = new javax.swing.JLabel();
        greenChip = new javax.swing.JLabel();
        whiteChip1 = new javax.swing.JLabel();
        blackChip1 = new javax.swing.JLabel();
        redChip1 = new javax.swing.JLabel();
        greenChip1 = new javax.swing.JLabel();
        blueChip1 = new javax.swing.JLabel();
        setBlindsPan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        doneButton = new javax.swing.JButton();
        dontPay = new javax.swing.JButton();
        foldCheckBet = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        doneFCB = new javax.swing.JButton();
        foldRB = new javax.swing.JRadioButton();
        checkRB = new javax.swing.JRadioButton();
        betRB = new javax.swing.JRadioButton();
        betTF = new javax.swing.JTextField();
        flip = new javax.swing.JButton();
        bigBlind = new javax.swing.JButton();
        smallBlind = new javax.swing.JButton();
        buttons = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(1300, 818));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        flop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playing-card-back.jpg"))); // NOI18N
        jPanel1.add(flop);
        flop.setBounds(910, 290, 70, 100);

        flop1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playing-card-back.jpg"))); // NOI18N
        jPanel1.add(flop1);
        flop1.setBounds(910, 290, 70, 100);

        flop2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playing-card-back.jpg"))); // NOI18N
        flop2.setToolTipText("");
        jPanel1.add(flop2);
        flop2.setBounds(910, 290, 71, 100);

        TURN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playing-card-back.jpg"))); // NOI18N
        jPanel1.add(TURN);
        TURN.setBounds(910, 290, 70, 100);

        RIVER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playing-card-back.jpg"))); // NOI18N
        jPanel1.add(RIVER);
        RIVER.setBounds(910, 290, 70, 100);

        deck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playing-card-back.jpg"))); // NOI18N
        jPanel1.add(deck);
        deck.setBounds(1000, 290, 70, 100);

        card1b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playing-card-back.jpg"))); // NOI18N
        card1b.setBorderPainted(false);
        card1b.setContentAreaFilled(false);
        jPanel1.add(card1b);
        card1b.setBounds(570, 460, 83, 112);

        card2b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playing-card-back.jpg"))); // NOI18N
        card2b.setBorderPainted(false);
        card2b.setContentAreaFilled(false);
        jPanel1.add(card2b);
        card2b.setBounds(650, 460, 83, 112);

        p2c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playing-card-back-2.jpg"))); // NOI18N
        jPanel1.add(p2c1);
        p2c1.setBounds(130, 240, 100, 71);

        p2c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playing-card-back-2.jpg"))); // NOI18N
        jPanel1.add(p2c2);
        p2c2.setBounds(130, 320, 100, 71);

        p3c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playing-card-back.jpg"))); // NOI18N
        jPanel1.add(p3c1);
        p3c1.setBounds(280, 470, 71, 100);

        p3c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playing-card-back.jpg"))); // NOI18N
        jPanel1.add(p3c2);
        p3c2.setBounds(360, 470, 71, 100);

        p4c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playing-card-back.jpg"))); // NOI18N
        jPanel1.add(p4c1);
        p4c1.setBounds(280, 140, 71, 100);

        p4c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playing-card-back.jpg"))); // NOI18N
        jPanel1.add(p4c2);
        p4c2.setBounds(370, 140, 71, 100);

        p5c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playing-card-back.jpg"))); // NOI18N
        jPanel1.add(p5c1);
        p5c1.setBounds(580, 130, 71, 100);

        p5c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playing-card-back.jpg"))); // NOI18N
        jPanel1.add(p5c2);
        p5c2.setBounds(660, 130, 71, 100);

        p6c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playing-card-back.jpg"))); // NOI18N
        jPanel1.add(p6c1);
        p6c1.setBounds(870, 130, 71, 100);

        p6c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playing-card-back.jpg"))); // NOI18N
        jPanel1.add(p6c2);
        p6c2.setBounds(950, 130, 70, 100);

        whiteChip.setText("White Chip ");
        whiteChip.setOpaque(true);
        jPanel1.add(whiteChip);
        whiteChip.setBounds(930, 500, 80, 30);

        blackChip.setText("Black Chip");
        blackChip.setOpaque(true);
        jPanel1.add(blackChip);
        blackChip.setBounds(930, 540, 80, 20);

        redChip.setText("Red Chip");
        redChip.setOpaque(true);
        jPanel1.add(redChip);
        redChip.setBounds(930, 570, 80, 30);

        blueChip.setText("Blue Chip");
        blueChip.setOpaque(true);
        jPanel1.add(blueChip);
        blueChip.setBounds(930, 650, 80, 30);

        greenChip.setText("Green Chip");
        greenChip.setOpaque(true);
        jPanel1.add(greenChip);
        greenChip.setBounds(930, 610, 80, 20);

        whiteChip1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        whiteChip1.setText("10");
        whiteChip1.setOpaque(true);
        jPanel1.add(whiteChip1);
        whiteChip1.setBounds(1050, 500, 80, 30);

        blackChip1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blackChip1.setText("6 ");
        blackChip1.setOpaque(true);
        jPanel1.add(blackChip1);
        blackChip1.setBounds(1050, 540, 80, 20);

        redChip1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        redChip1.setText("4");
        redChip1.setOpaque(true);
        jPanel1.add(redChip1);
        redChip1.setBounds(1050, 570, 80, 30);

        greenChip1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        greenChip1.setText("2");
        greenChip1.setOpaque(true);
        jPanel1.add(greenChip1);
        greenChip1.setBounds(1050, 610, 80, 20);

        blueChip1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blueChip1.setText("2");
        blueChip1.setOpaque(true);
        jPanel1.add(blueChip1);
        blueChip1.setBounds(1050, 650, 80, 30);

        setBlindsPan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setBlindsPan.setLayout(null);

        jLabel2.setText("Pay Small Blind ($25)?:");
        setBlindsPan.add(jLabel2);
        jLabel2.setBounds(30, 30, 170, 15);

        doneButton.setText("Yes!");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });
        setBlindsPan.add(doneButton);
        doneButton.setBounds(60, 60, 80, 40);

        dontPay.setText("Fold");
        setBlindsPan.add(dontPay);
        dontPay.setBounds(60, 110, 80, 40);

        jPanel1.add(setBlindsPan);
        setBlindsPan.setBounds(60, 600, 210, 200);

        foldCheckBet.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        foldCheckBet.setLayout(null);

        jLabel3.setText("Would you like to:");
        foldCheckBet.add(jLabel3);
        jLabel3.setBounds(20, 10, 130, 20);

        doneFCB.setText("Done");
        doneFCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneFCBActionPerformed(evt);
            }
        });
        foldCheckBet.add(doneFCB);
        doneFCB.setBounds(20, 140, 170, 40);

        foldCheckBetGroup.add(foldRB);
        foldRB.setText("Fold?");
        foldRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foldRBActionPerformed(evt);
            }
        });
        foldCheckBet.add(foldRB);
        foldRB.setBounds(20, 40, 57, 22);

        foldCheckBetGroup.add(checkRB);
        checkRB.setSelected(true);
        checkRB.setText("Check?");
        foldCheckBet.add(checkRB);
        checkRB.setBounds(20, 70, 70, 22);

        foldCheckBetGroup.add(betRB);
        betRB.setText("Bet?");
        foldCheckBet.add(betRB);
        betRB.setBounds(20, 100, 53, 22);

        betTF.setText("How Much?");
        betTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betTFActionPerformed(evt);
            }
        });
        foldCheckBet.add(betTF);
        betTF.setBounds(90, 100, 100, 25);

        jPanel1.add(foldCheckBet);
        foldCheckBet.setBounds(310, 600, 220, 200);

        flip.setText("Flip Card");
        jPanel1.add(flip);
        flip.setBounds(780, 550, 100, 30);

        bigBlind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bigblinddone.png"))); // NOI18N
        bigBlind.setContentAreaFilled(false);
        jPanel1.add(bigBlind);
        bigBlind.setBounds(800, 210, 70, 70);

        smallBlind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Small-Blind-Button-SY-Q58DONE-.png"))); // NOI18N
        smallBlind.setContentAreaFilled(false);
        jPanel1.add(smallBlind);
        smallBlind.setBounds(810, 450, 70, 60);

        buttons.setText("buttons?");
        jPanel1.add(buttons);
        buttons.setBounds(780, 700, 110, 50);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pokertable.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void flipActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doneButtonActionPerformed

    private void doneFCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneFCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doneFCBActionPerformed

    private void foldRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foldRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foldRBActionPerformed

    private void betTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_betTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameTable.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameTable.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameTable.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameTable.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GameTable().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GameTable.class.getName()).log(Level.SEVERE,
                                                                    null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RIVER;
    private javax.swing.JLabel TURN;
    private javax.swing.JRadioButton betRB;
    private javax.swing.JTextField betTF;
    private javax.swing.JButton bigBlind;
    private javax.swing.JLabel blackChip;
    private javax.swing.JLabel blackChip1;
    private javax.swing.JLabel blueChip;
    private javax.swing.JLabel blueChip1;
    private javax.swing.JButton buttons;
    private javax.swing.JButton card1b;
    private javax.swing.JButton card2b;
    private javax.swing.JRadioButton checkRB;
    private javax.swing.JLabel deck;
    private javax.swing.JButton doneButton;
    private javax.swing.JButton doneFCB;
    private javax.swing.JButton dontPay;
    private javax.swing.JButton flip;
    private javax.swing.JLabel flop;
    private javax.swing.JLabel flop1;
    private javax.swing.JLabel flop2;
    private javax.swing.JPanel foldCheckBet;
    private javax.swing.ButtonGroup foldCheckBetGroup;
    private javax.swing.JRadioButton foldRB;
    private javax.swing.JLabel greenChip;
    private javax.swing.JLabel greenChip1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel p2c1;
    private javax.swing.JLabel p2c2;
    private javax.swing.JLabel p3c1;
    private javax.swing.JLabel p3c2;
    private javax.swing.JLabel p4c1;
    private javax.swing.JLabel p4c2;
    private javax.swing.JLabel p5c1;
    private javax.swing.JLabel p5c2;
    private javax.swing.JLabel p6c1;
    private javax.swing.JLabel p6c2;
    private javax.swing.JLabel redChip;
    private javax.swing.JLabel redChip1;
    private javax.swing.JPanel setBlindsPan;
    private javax.swing.JButton smallBlind;
    private javax.swing.JLabel whiteChip;
    private javax.swing.JLabel whiteChip1;
    // End of variables declaration//GEN-END:variables

    public JButton getFlip() {
        return flip;
    }

    public JLabel getFlop() {
        return flop;
    }

    public JLabel getFlop1() {
        return flop1;
    }

    public JLabel getFlop2() {
        return flop2;
    }

    public JLabel getRIVER() {
        return RIVER;
    }

    public JLabel getTURN() {
        return TURN;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JButton getCard1b() {
        return card1b;
    }

    public JButton getCard2b() {
        return card2b;
    }

    public JLabel getDeck() {
        return deck;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getP2c1() {
        return p2c1;
    }

    public JLabel getP2c2() {
        return p2c2;
    }

    public JLabel getP3c1() {
        return p3c1;
    }

    public JLabel getP3c2() {
        return p3c2;
    }

    public JLabel getP4c1() {
        return p4c1;
    }

    public JLabel getP4c2() {
        return p4c2;
    }

    public JLabel getP5c1() {
        return p5c1;
    }

    public JLabel getP5c2() {
        return p5c2;
    }

    public JLabel getP6c1() {
        return p6c1;
    }

    public JLabel getP6c2() {
        return p6c2;
    }

    public JPanel getSetBlindsPan() {
        return setBlindsPan;
    }

    public JLabel getBlackChip() {
        return blackChip;
    }

    public JLabel getBlackChip1() {
        return blackChip1;
    }

    public JLabel getBlueChip() {
        return blueChip;
    }

    public JLabel getBlueChip1() {
        return blueChip1;
    }

    public JButton getDoneButton() {
        return doneButton;
    }

    public JLabel getGreenChip() {
        return greenChip;
    }

    public JLabel getGreenChip1() {
        return greenChip1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getRedChip() {
        return redChip;
    }

    public JLabel getRedChip1() {
        return redChip1;
    }

    public JLabel getWhiteChip() {
        return whiteChip;
    }

    public JLabel getWhiteChip1() {
        return whiteChip1;
    }

    public JButton getDontPay() {
        return dontPay;
    }

    public JRadioButton getBetRB() {
        return betRB;
    }

    public JTextField getBetTF() {
        return betTF;
    }

    public JRadioButton getCheckRB() {
        return checkRB;
    }

    public JButton getDoneButton1() {
        return doneFCB;
    }

    public JPanel getFoldCheckBet() {
        return foldCheckBet;
    }

    public ButtonGroup getFoldCheckBetGroup() {
        return foldCheckBetGroup;
    }

    public JRadioButton getFoldRB() {
        return foldRB;
    }

    public JButton getBigBlind() {
        return bigBlind;
    }

    public JButton getButtons() {
        return buttons;
    }

    public JButton getSmallBlind() {
        return smallBlind;
    }

    public JButton getDoneFCB() {
        return doneFCB;
    }

}
